#!/bin/bash
SERVICE_FILE=/usr/lib/systemd/system/app.service
BIN=/valiu/valor

[ ! -f $SERVICE_FILE ] || mv $SERVICE_FILE /tmp/$(basename $SERVICE_FILE).old
[ ! -f $BIN ] || mv $BIN /tmp/$(basename $BIN).old
